version : '3'
services:
  web:
    build: .
    ports:
      - 80:3000
    volumes:
      - .:/web
    container_name: webapp
    entrypoint: sh /web/startup.sh
    env_file: .env
    stdin_open: true
    tty: true
    links:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: db
    env_file: .env
