version : '3'
services:
  web:
    build: .
    ports:
      - 80:3000
    volumes:
      - .:/web
    entrypoint: sh /web/startup.sh
    links:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: web
